#Group 35
#Name: Yunfan Li, Xiang Li, Zhicheng Fu
#Class: CS544-001

all:
	pdflatex anotated.tex
	bibtex anotated.aux
	bibtex latex.aux
	pdflatex anotated.tex

clean:
	rm -f *.pdf *.ps *.dvi *.out *.log *.aux *.bbl *.blg *.pyg
